name: Build editors-picks-uploader

on:
  pull_request:
  push: # Do not rely on `push` for PR CI - see https://github.com/guardian/mobile-apps-api/pull/2741#issuecomment-1777653733
    branches:
      - main # Optimal for GHA workflow caching - see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  workflow_dispatch: {}

jobs:
  editors-picks-uploader:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'test;universal:packageBin'

      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml

      - uses: guardian/actions-riff-raff@v4
        with:
          configPath: riff-raff.yaml
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: Content Platforms::editors-picks-uploader-lambda
          buildNumberOffset: 71
          contentDirectories: |
            editors-picks-uploader:
              - target/universal/editors-picks-uploader.zip
