name: Build editors-picks-uploader

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  editors-picks-uploader:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'test;universal:packageBin'

      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: ${{secrets.GU_RIFF_RAFF_ROLE_ARN}}

      - uses: guardian/actions-riff-raff@v2
        with:
          configPath: riff-raff.yaml
          projectName: Content Platforms::editors-picks-uploader-lambda
          buildNumberOffset: 71
          contentDirectories: |
            editors-picks-uploader:
              - target/universal/editors-picks-uploader.zip